import os 

AWS_S3_BUCKEDT_NAME ="wafer-fault"
MONGO_DATABASE_NAME="PWSKILLS"
MONGO_COLLECTION_NAME="WAFERFAULT"

TARGET_COLUMN="quality"
MONGO_DB_URL=

MODEL_FILE_NAME="model"
MODEL_FILE_EXTENSION=".pkl"